---
env:
  es2021: true
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2021
  sourceType: module
  ecmaFeatures:
    jsx: true
  project: ./tsconfig.json
settings:
  import/parsers:
    typescript-eslint/parser:
      - '.ts'
      - '.tsx'
  import/resolver:
    node:
      extensions:
        - '.js'
        - '.jsx'
        - '.ts'
        - '.tsx'
      moduleDirectory:
        - node_modules
        - app/
        - middleware/
        - pages/
        - public/
        - redux/
    typescript:
      alwaysTryTypes: true
  react:
    pragma: React
    version: detect
extends:
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:jsx-a11y/recommended
  - plugin:prettier/recommended
  - plugin:@next/next/recommended
plugins:
  - react
  - prettier
  - jsx-a11y
  - import
rules:
  prettier/prettier: error
  no-restricted-imports: error
  import/order:
    - warn
    - groups:
        - builtin
        - external
        - internal
      pathGroups:
        - pattern: react
          group: external
          position: before
      pathGroupsExcludedImportTypes:
        - react
      newlines-between: ignore
      alphabetize:
        order: asc
        caseInsensitive: true
  typescript-eslint/indent: off
  typescript-eslint/explicit-module-boundary-types: off
  typescript-eslint/no-explicit-any: off
  typescript-eslint/explicit-function-return-type: off
  react/jsx-one-expression-per-line: off
  react/prop-types: off
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  semi:
    - error
    - always
  object-curly-newline: off
  arrow-body-style: off
  react/jsx-props-no-spreading: off
  implicit-arrow-linebreak: off
  func-names: off
  operator-linebreak: off
  function-paren-newline: off
  react/require-default-props: off
  react/jsx-curly-newline: off
  react/jsx-wrap-multilines: off
  react/destructuring-assignment: off
  no-shadow: off
  typescript-eslint/no-shadow: off
  react/no-array-index-key: off
