---
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:jsx-a11y/recommended
plugins:
  - react
  - eslint-plugin-import
  - react-hooks
  - prettier
  - jsx-a11y
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
env:
  browser: true
  node: true
  es6: true
settings:
  import/resolver:
    alias:
      map:
        - - '@'
          - './src'
rules:
  prettier/prettier: warn
  react/prop-types: warn
  jsx-a11y/no-autofocus: off
  jsx-a11y/click-events-have-key-events: off
  react/display-name: off
  import/order:
    - error
    - groups:
        - builtin
        - external
        - index
      pathGroups:
        - pattern: react
          group: external
          position: before
        - pattern: '@/**'
          group: external
          position: after
      pathGroupsExcludedImportTypes:
        - react
        - '@/**'
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
