export default {
  '/services': 'services',
  '/users': 'users',
  '/patients': 'patients',
  '/calendar': 'calendar',
  '/calendar/day': 'calendar',
  '/calendar/week': 'calendar',
  '/calendar/month': 'calendar',
  '/crm': 'crm board',
  '/settings': 'settings',
  '/analytics/services': 'services statistics',
  '/analytics/general': 'general statistics',
  '/analytics/doctors': 'doctors statistics',
  '/analytics/activity-logs': 'activity logs',
  '/messages': 'messages',
  '/doctor': 'schedules',
  '/confirmation': 'confirmation',
  '/login': 'authentication',
  '/clinics': 'select a clinic',
  '/create-clinic': 'create clinic',
  '/register': 'create new account',
  '/error': 'error',
};
