export default {
  'about clinic': 'About clinic',
  'accept invitation': 'Accept invitation',
  'accept invitation message':
    'Fill in the fields below to accept the invitation.',
  access_blocked: 'Blocked access',
  access_blocked_message:
    'Your access to this clinic was blocked, please contact the manager of the clinic for more information.',
  account_created_success:
    'The account was created successfully. Please enter the details of the clinic.',
  'account information': 'Account details',
  'account settings': 'Account settings',
  actions: 'Actions',
  'activity logs': 'Activity log',
  'add a comment': 'Add a comment …',
  'add appointment': 'Add an appointment',
  add_appointment_cabinet: 'Office',
  add_cabinet: 'Add office',
  'add category': 'Add category',
  'add doctor': 'Add doctor',
  'added by': 'Added by {1} to date {2}',
  addedby: 'Added by',
  'add holiday': 'Add holiday',
  'add image': 'Add image',
  'add manager': 'Add manager',
  add_new_appointment: 'Add new appointment',
  add_new_card: 'Add new card',
  'add new color': 'Add new colour',
  'add new column': 'Add column',
  'add new user': 'Add user',
  'add note': 'Add note',
  'add one +': 'Add +',
  'add patient': 'Add patient',
  addpatientxrayimage: 'Added an X-Ray image to a patient',
  'add pause': 'Add pause',
  'add payment': 'Add payment',
  'add rate': 'Add exchange rate',
  'add receptionist': 'Add receptionist',
  add_seats: 'Add seats',
  'add service': 'Add service',
  add_tag_to_patient: 'Add tag',
  add_to_apple_calendar: 'Add to Apple Calendar',
  add_to_google_calendar: 'Add to Google Calendar',
  'add user': 'Add user',
  add_xray_image: 'Add X-Ray image',
  administrators: 'Managers',
  all: 'All',
  all_articles: 'All articles',
  'all categories': 'All categories',
  'all doctors': 'All doctors',
  allow_access: 'Allow access',
  'all services': 'All services',
  'all statuses': 'All statuses',
  all_tags: 'All',
  'all time': 'All time',
  'all users': 'All users',
  'already have an account': 'Already have an account',
  amount: 'Amount',
  analytics: 'Analytics',
  analytics_clients_new_old: 'New clients / Repeated clients',
  analytics_clients_source: 'Source of clients',
  analytics_doctor_conversion: 'Conversion / Doctor',
  analytics_doctor_income: 'Income / Doctor',
  analytics_doctor_visits: 'Visits / Doctor',
  analytics_executed: 'Executed',
  analytics_paid_unpaid: 'Paid / Debts',
  analytics_planned: 'Planned',
  analytics_services_completed_planned: 'Performed / planned services',
  analytics_total_messages: 'Total sent messages',
  analytics_total_visits: 'Total visits',
  analytics_treated_patients: 'Patients with treatment plan',
  'animate appointments before': 'Notify about appointment in advance',
  api_address: 'API address',
  api_key: 'API key',
  'app initialization': 'Initialization of application',
  'applicable on all teeth': 'Applicable to all teeth',
  'applicable on single tooth': 'Applicable to a single tooth',
  'application settings': 'Application settings',
  apply: 'Apply',
  'apply filters': 'Apply filters',
  'apply to all': 'Apply to all',
  appointment: 'Appointment',
  appointment_animation_timer:
    'Indicate how long the appointments must be animated beforehand',
  appointment_cabinet: 'Office',
  appointment_create: 'Create appointment',
  appointment_createNew: 'Create new appointment',
  appointment_createPatient: 'Create patient',
  appointment_date: 'Date',
  appointment_details: 'Details on appointment',
  appointment_doctor: 'Doctor',
  appointment_hours: 'Hour',
  appointment_name: 'Surname Name',
  appointment_newClient: 'New client',
  appointment_noOptions: 'There are no options for display',
  appointment_noPatient: 'No client selected',
  appointment_notes: 'Notes',
  appointment_patient: 'Patient',
  appointment_phone: 'Telephone',
  appointment_placeholder: 'Type to search',
  appointments: 'Appointments',
  appointment_searching: 'Search',
  appointment_service: 'Service',
  'appointments notes': 'Visits',
  appointment_source: 'Source',
  'appointment status': 'Status of appointment',
  appointment_to_doctor: 'Appointment to doctor',
  appointment_urgent: 'Urgent appointment',
  app_settings_tags: 'Tags of patients',
  app_settings_time_before_on_site: 'Time before being on site',
  'are you sure you want to delete this category?':
    'Are you sure you want to delete this category?',
  'are you sure you want to delete this service?':
    'Are you sure you want to delete this service?',
  'are you sure you want to delete this user?':
    'Are you sure you want to delete this user?',
  'are you sure you want to restore this service?':
    'Are you sure you want to restore this service?',
  ' article_updated_at': 'Updated on {1}',
  ' at': 'at',
  'authenticate with yclients account': 'Log in with Yclients account',
  ' authentication': 'Login',
  ' back_to_payment_history': 'Back to payment history',
  ' billing_details': 'Payment details',
  ' birthday': 'Date of birth',
  ' birthdaycongrats': 'Birthday greetings',
  ' birthdaycongratsdesc':
    'This message will be sent to patients on their birthday (if indicated)',
  ' block_access': 'Block access',
  ' braces': 'Dental appliance',
  'braces service': 'Service for dental appliance',
  'braces settings': 'Settings of dental appliances',
  ' budget': 'Budget',
  ' cabinet_name_exists': 'Office with such name already exists',
  ' calendar': 'Calendar',
  'calendar legend': 'Legend of statutes',
  ' call_answered': 'Discussion took place',
  ' call_busy': 'Busy',
  ' call_direction_with_time': 'Call by {1} {2}',
  call_download: 'Download',
  call_failed: 'Call failed',
  call_from: 'from',
  call_incoming: 'Incoming',
  call_listen: 'Listen',
  call_noanswer: 'No answer',
  call_outgoing: 'Outgoing',
  call_to: 'to',
  call_unknown: 'Unknown status',
  can: 'Can',
  cancel: 'Cancel',
  canceled: 'Cancelled',
  canceled_by_patient: 'Cancelled by patient',
  'canceled reason': 'Reason of cancel',
  canceledreason: 'Reason of cancel',
  cancel_schedule: 'Cancel',
  cancel_schedule_message:
    'For what reason do you want to cancel visit to doctor?',
  cancel_schedule_title: 'Cancel of appointment',
  cancel_subscription_confirmation:
    'Are you sure you want to cancel subscription?',
  can_manage_others_schedules: 'Can manage appointments of other people',
  can_manage_own_schedules: 'Can manage appointments independently',
  cannot: 'Cannot',
  cashier: 'Cashier',
  categories: 'Categories',
  'change column color': 'Change colour',
  'change password message': 'Password must contain at least 6 characters.',
  chart_clientsnewreturn: 'New clients / Repeated clients',
  chart_clientssource: 'Source of clients',
  chart_doctorsconversion: 'Conversion / Doctor',
  chart_doctorsincome: 'Income / Doctor',
  chart_doctorsvisits: 'Visits / Doctor',
  chart_income: 'Paid / Debts',
  chart_messages: 'Total sent messages',
  chart_services: 'Performed / planned services',
  chart_treatedclients: 'Patients with treatment plan',
  chart_visits: 'Total visits',
  checkout_no_services: 'You did not select any service.',
  checkout_select_below:
    'Select services by entering their names in the field below.',
  'choose match': 'Choose field',
  'chose...': 'Choose …',
  'click on button below to accept the invitation':
    'Click on the button below to accept the invitation',
  clinic: 'Clinic',
  clinic_cabinet_confirmation_request:
    'Are you sure you want to delete this office',
  clinic_cabinet_doctor_deletion_confirmation:
    'Are you sure you want to eliminate this doctor',
  clinic_cabinets: 'Offices of clinic',
  clinic_cabinets_tag_field: 'Add new office',
  clinic_cabinets_tag_helper: 'Enter name of office and press Enter to save',
  'clinic currency': 'Currency of clinic',
  cliniccurrencyatpaymenttime: 'Currency',
  clinic_current_cabinets: 'Current offices',
  clinic_delete_requested: 'Received request',
  clinic_delete_requested_message:
    'Your request was received, we will contact you in a short time to confirm all details',
  clinic_has_no_working_hours: 'Clinic has day off for {1}.',
  'clinic name': 'Name of clinic',
  'clinic profit': 'Profit of clinic',
  clinic_settings: 'Clinic settings',
  close: 'Close',
  'column name': 'Column name',
  comment: 'Comment',
  'company details': 'Company details',
  completedat: 'Date of completion',
  'completed by': 'completed by {1} at date {2}',
  completedby: 'Completed by',
  complete_deal: 'Confirm',
  'completed. free.': 'Completed. Free of charge.',
  'completed not paid': 'Completed unpaid',
  completednotpaid: 'Completed unpaid',
  completedpaid: 'Paid',
  'completed services': 'Performed services',
  confirm: 'Confirm',
  confirmation: 'Confirmation',
  'confirmation link': 'Confirmation link',
  confirmed: 'Confirmed',
  'confirming schedule': 'Confirm appointment…',
  'confirm new password': 'Confirm new password',
  'confirm password': 'Confirm new password',
  connect: 'Connect',
  'connect another page': 'Connect another page',
  connected_facebook_page: 'Connected to page {1}',
  'connect facebook': 'Connect Facebook page',
  connect_social_message:
    'Connect social networks in order to generate more leads and increase number of clients.',
  connect_social_networks: 'Connect social networks',
  country: 'Country',
  'country code': 'Code of country',
  covid_notice:
    'If you have fever, cough, throat pains or other symptoms similar to COVID-19 virus, please announce us beforehand and suspend the visit. Thank you for understanding!',
  covid_notice_title: '*Important!',
  create: 'Create',
  createappointment: 'Created an appointment',
  createcategory: 'Created a category',
  'create clinic': 'Create clinic',
  createClinic: 'Created a clinic',
  createclinicpaymentaction: 'Registered a payment',
  'created at': 'Created on',
  'created by': 'Created by',
  createinvoiceaction: 'Created an invoice',
  createinvoiceserviceaction: 'A service was added to invoice',
  'create message': 'Create message',
  'create new account': 'Create account',
  'create new password': 'Create new password',
  createnoteaction: 'Created a note',
  'create patient': 'Add patient',
  createpatient: 'Created a patient',
  createpatientaction: 'Created the patient',
  createpatientfromschedule: 'Created a patient from appointment',
  createpatientfromscheduleaction: 'Created a patient from appointment',
  createpatientnote: 'Added a note to a patient',
  createscheduleaction: 'Created an appointment',
  createservice: 'Created a service',
  createtreatmentplanserviceaction: 'Added a service to the treatment plan',
  createuser: 'Created a user',
  createvisitaction: 'Created a visit',
  crm_add_reminder: 'Add task',
  crm_columns: 'Columns',
  crm_filter_all_deals: 'All',
  crm_filter_all_reminders: 'All',
  crm_filter_closed_successfully: 'Completed successfully',
  crm_filter_current_week_reminders: 'The next 7 days',
  crm_filter_expired_tasks: 'Expired',
  crm_filter_my_deals: 'Just mine',
  crm_filter_not_realized: 'Unrealized',
  crm_filter_opened_deals: 'Opened',
  crm_filter_shortcuts_expired_tasks: 'With expired tasks',
  crm_filter_shortcuts_today_reminders: 'With tasks for today',
  crm_filter_states: 'Statuses',
  crm_filter_today_reminders: 'For today',
  crm_filter_tomorrow_reminders: 'For tomorrow',
  crm_filter_without_tasks: 'Without tasks',
  crm_log_action_changeclinic: 'Modified clinic',
  crm_log_action_changestatus: 'Modified status',
  crm_log_action_createschedule: 'Created an appointment for the date',
  crm_log_action_linkpatient: 'Attributed the patient',
  crm_log_action_removed: 'Action in the log is eliminated',
  crm_move_to_clinic: 'Move to another branch',
  crm_new_note: 'New note',
  crm_new_reminder: 'New task',
  crm_no_reminders: 'There are no tasks',
  crm_reminder_at: 'at',
  crm_reminder_complete: 'Complete',
  crm_reminder_date: 'For',
  crm_reminder_enter_result: 'Add result of task',
  crm_reminder_for: 'For',
  crm_reminder_result: 'Result',
  crm_reminders: 'Tasks',
  crm_reminders_all_tasks: 'All tasks',
  crm_reminders_completed_tasks: 'Completed tasks',
  crm_reminders_expired_tasks: 'Expired tasks',
  crm_reminders_my_tasks: 'My tasks',
  crm_reminder_today: 'Today at',
  crm_reminder_type: 'Type',
  crm_reminder_type_contact: 'Appeal',
  crm_reminder_type_meeting: 'Meeting',
  crm_reminder_user: 'Responsible person',
  crm_settings: 'CRM settings',
  csv_max_rows_exceeded:
    'The loaded file contains more rows than the maximum allowed number.',
  currency: 'Currency',
  current_bill: 'Current tax',
  'current password': 'Current password',
  'current password is required': 'Introduce current password',
  date: 'Date',
  dateandtime: 'Time of beginning',
  day: 'Day',
  'day off': 'Day off',
  'day schedules': 'Appointments for one day',
  'days starting today': 'today',
  'days up to today': 'days before today',
  deal_phone_call_date: 'Appeal by {2} {3}: {4}',
  debt: 'Debts',
  debts: 'Debts',
  default_card: 'Default card',
  'default currency': 'Basic currency',
  delaytime: 'Time of delay',
  delete: 'Delete',
  'delete appointment': 'Delete appointment',
  deleteappointment: 'Deleted an appointment',
  'delete appointment message':
    'Are you sure you want to delete this appointment?',
  'delete category': 'Delete category',
  deletecategory: 'Deleted a category',
  'delete clinic': 'Delete clinic',
  delete_clinic_message: 'Are you sure you want to delete the current clinic?',
  'delete column': 'Delete column',
  delete_crm_column: 'Delete{1}',
  delete_crm_column_message: 'Are you sure you want to delete this column?',
  deleted: 'Deleted',
  delete_deal_message: 'Are you sure you want to delete this data?',
  delete_deal_title: 'Delete title',
  deletedinvoiceaction: 'Cancelled a payment',
  'delete image': 'Delete image',
  deleteimageconfirmation: 'Please confirm that you want to delete this image.',
  delete_invitation: 'Delete invitation',
  delete_invitation_message: 'Are you sure you want to delete invitation?',
  'delete message': 'Delete message',
  delete_message_desc: 'Are you sure you want to delete this message?',
  deletenoteaction: 'Deleted a note',
  'delete patient': 'Delete patient',
  deletepatient: 'Deleted a patient',
  delete_patient_message: 'Are you sure you want to delete this patient?',
  deletescheduleaction: 'Deleted an appointment',
  'delete service': 'Delete service',
  deleteservice: 'Deleted a service',
  delete_subscription: 'Termination of contract',
  delete_subscription_info:
    'At the termination of the contract, no tax will be collected according to the selected plan, and the access to the application will be limited.',
  'delete user': 'Delete user',
  deleteuser: 'Deleted a user',
  description: 'Description',
  destination: 'Destination',
  details: 'Details',
  diagnosis: 'Diagnostics',
  'did not came': 'Did not come',
  'did not come': 'Did not come',
  "didn't show up": 'Did not come',
  disable: 'Disable',
  disconnect: 'Disconnect',
  discount: 'Discount',
  discount_notice: 'Save 15% of monthly tariff',
  doctor: 'Doctor',
  doctor_calendar_color: 'Colour of appointments in calendar',
  doctor_do_not_provide_service:
    'The selected doctor does not provide this service!',
  doctor_is_fired: 'The doctor is dismissed!',
  doctorname: 'Name of doctor',
  'doctor part': 'Salary of doctor',
  doctors: 'Doctors',
  'doctors statistics': 'Statistics of doctors',
  'doctors who provide this service': 'Doctors who offer this service',
  doctor_vacation_message: 'The doctor is on vacation for the given day',
  'domain name': 'Domain name',
  "don't have an account": 'You do not have an account',
  duration: 'Duration',
  edit: 'Edit',
  'edit appointment': 'Edit appointment',
  editappointment: 'Edited an appointment',
  'edit category': 'Edit category',
  editcategory: 'Edited a category',
  editclinic: 'Edited clinic',
  edit_connection: 'Edit connection',
  'edit message': 'Edit message',
  editpatient: 'Edited a patient',
  edit_pause: 'Edit pause',
  'edit profile': 'Edit account',
  'edit service': 'Edit service',
  editservice: 'Edited a service',
  'edit user': 'Edit user',
  edituser: 'Edited a user',
  editvisitnote: 'Edited note at visit',
  edit_working_hours: 'Edit working hours',
  email: 'Email',
  email_invalid_message: 'Email address is not valid',
  email_with_instructions_was_sent: 'Sent you an email with instructions',
  enable: 'Enable',
  'end time': 'End',
  endtime: 'Time of end',
  'enter a new password': 'Enter a new password',
  'enter category name': 'Enter category name',
  'enter doctor name or phone': 'Enter name or phone number',
  'enter guide name': 'Enter guide name',
  'enter new message': 'Enter a new message',
  'enter new note': 'Enter a new note',
  'enter patient name or phone': 'Enter name or phone number',
  'enter reason below': 'Enter reason below',
  'enter service name': 'Enter service name',
  enter_the_note: 'Enter note',
  'euro debt': 'Debt Euro',
  'exchange rate': 'Exchange rate',
  exchangeratevalueatpaymenttime: 'The exchange rate',
  executedcount: 'Executed',
  'existent patient': 'Existent patient',
  expectations: 'Scheduled',
  'fallen brackets': 'Fallen brackets',
  fill_required_fields: 'Fill in all mandatory fields',
  filter: 'Filters',
  finalize: 'Complete',
  'finalize treatment': 'Completion of treatment',
  finalizetreatment: 'Completed a treatment',
  finalizing_treatment: 'Treatment is being completed',
  'final phase': 'Final stage',
  finished: 'Completed',
  fired: 'Dismissed',
  'first name': 'Name',
  firstname: 'Surname',
  first_n_last_name: 'Surname Name',
  'forgot your password': 'Have you forgotten the password?',
  'for payment': 'Due for payment',
  friday: 'Friday',
  friend: 'Friends',
  from: 'from',
  fullname: 'Full name',
  gender: 'Sex',
  general: 'General',
  'general statistics': 'General statistics',
  'go back': 'Back',
  go_to: 'Go to',
  'go to home': 'To homepage',
  help_crm_add_reminder_message: 'Click here to add a new task',
  help_tech_support_message:
    'Click here if you encountered any problems in the use of the application or an error occurred, in order to discuss with the technical support.',
  hidden: 'Hidden',
  'hide from calendar': 'Hide from calendar',
  'history of changes': 'History of changes',
  holidaycongrats: 'Congratulations on the occasion of holiday',
  holidaycongratsdesc:
    'This message will be sent to all patients each year on the date selected below',
  holidays: 'Vacations',
  hour: 'Hour',
  hours: 'Hours',
  'how long the patient was late': 'How late the patient will be',
  how_to_get_api_info: 'How do I find these data?',
  how_to_get_moizvonki_data: 'How can I obtain API data for Moizvonki.ru?',
  id: 'Identifier',
  importedeurodebt: 'Imported debt Euro',
  import_end_time: 'Time of end',
  'importing data in progress': 'Importing of data in progress',
  import_n_patients: 'Imported {1} patients',
  import_n_schedules: 'Imported {1} appointments',
  import_n_services: 'Imported {1} services',
  'import patients': 'Importing of patients',
  'import schedules': 'Importing of appointments',
  'import services': 'Import services',
  import_services_note:
    'Note: Services without a valid name will not be imported.',
  import_start_date: 'Time of beginning',
  included: 'Included',
  'included services': 'Included Services',
  'initial phase': 'Initial stage',
  insert_at_least_3_characters: 'Enter more than 3 characters',
  integrations: 'Integrations',
  invitation_accepted_success: 'Invitation was accepted successfully',
  invitations: 'Invitations',
  'invitation sent': 'Sent invitation',
  invitation_sent_message:
    'A new email with invitation to your clinic was sent.',
  invite: 'Invite',
  'invite existent user': 'Invite existing user',
  'invite user': 'Invite user',
  invoice_already_paid: 'This invoice is already paid!',
  invoice_created: 'A new invoice was created!',
  is_clinic_day_off: 'It is day off',
  iscompleted: 'It is completed',
  is_doctor_holiday: 'The doctor is on vacation',
  'is urgent': 'It is urgent!',
  isurgent: 'It is urgent',
  is_user_day_off: 'The doctor has day off',
  "it's a day off": 'It is day off',
  'jpg or png, max size of 800kb': 'JPG or PNG, Maximum size 800kb',
  language: 'Language',
  languagedesc: 'Write message in each available language.',
  last_changes_list: 'Last modifications',
  'last month': 'Last month',
  'last name': 'Surname',
  lastname: 'Name',
  'last week': 'Last week',
  late: 'Is late',
  liabilities: 'Debts',
  link_patient: 'Assignment of patient',
  list: 'List',
  'loading statistics': 'The statistics is loaded',
  'log in to your account': 'Log in to your account',
  logout: 'Log-out',
  'logout message': 'Are you sure you want to log out?',
  malocclusion: 'Malocclusion',
  manage_payment_method: 'Manage payment method',
  manager: 'Manager',
  manage_seats: 'Manage seats',
  mandible: 'Mandible',
  map_all_fields: 'You did not indicate: {1}',
  'map doctors': 'Mapping doctors',
  'map services': 'Mapping services',
  maxillary: 'Maxillary',
  menu_crm_help_message:
    'Now you can rise relationships with your clients to another level. Click here to open the CRM panel where you can control the whole flow of patients.',
  menu_crm_help_title: 'Now CRM also',
  message: 'Text of message',
  message_exists: 'This type of message already exists',
  'message not delivered': 'Message was not sent',
  messages: 'SMS messages',
  'message text': 'Text of message',
  messagetext: 'Text of message',
  'message title': 'Title of message',
  messagetitledesc:
    'Title of message is visible only to you, patients will not see this title.',
  'message type': 'Type of message',
  'middle phase': 'Middle phase',
  'migrate data from yclients': 'Migration of data from Yclients',
  minutes: 'Minutes',
  moizvonki_connect_info: 'Moizvonki.ru API data',
  moizvonki_username_help: 'Email address used to log in to Moizvonki.ru',
  monday: 'Monday',
  month: 'Month',
  monthly: 'Monthly',
  months: 'Months',
  'move column to left': 'Move to the left',
  'move column to right': 'Move to the right',
  name: 'Name',
  n_contacts_only: 'Maximum {1} patients',
  'new password': 'New password',
  'new patient': 'Add new patient',
  next: 'Next',
  next_payment_info:
    'The following payment in the amount of {1} will be collected on {2}',
  'no appointment': 'Does not have appointment',
  'no available time': 'There is no available time',
  no_categories_message: 'There are no created categories:( ',
  'no data here yet': 'There are no data here',
  'no debts found': 'Does not have debts',
  'no description': 'There is no description',
  'no doctors yet': 'There is no doctor.',
  'no managers yet': 'There is no manager.',
  'no name specified': 'No name is specified',
  no_notes: 'There are no notes',
  'no options': 'There are no results',
  'no pending invitations': 'There are no pending invitations',
  'no phone number': 'It is not indicated',
  no_purchased_subscription: 'There are no subscriptions to display',
  no_recent_changes: 'There are no recent modifications',
  'no receptionists yet': 'There is no receptionist',
  'no results': 'No results found',
  'no schedules for this day': 'There are no appointments for this day',
  'no selected services': 'There are no selected services',
  no_services_message: 'There are still no services in this category :(',
  no_sms_alias_message:
    'SMS notifications service is not connected. In order to connect please contact us.',
  no_sms_messages: 'There are still no created messages',
  note: 'Note',
  notes: 'Notes',
  notetext: 'Text of note',
  'no treatment plan': 'Has no treatment plan',
  n_schedules_only: 'Maximum {1} appointments',
  n_services_only: 'Maximum {1} services',
  number: 'Number',
  occlusion: 'Occlusion',
  of: 'of',
  'offers braces services': 'Provides orthodontics services',
  onetimemessage: 'Message sent once',
  onetimemessagedesc:
    'ATTENTION! This message will be sent to all patients once immediately after you save the message',
  'on site': 'On site',
  onsite: 'On site',
  optional: 'Optional',
  or: 'or',
  'orthodontic plan': 'Orthodontic plan',
  other: 'Other',
  page_not_found: 'Page was not found',
  paid: 'Paid',
  paidamount: 'Paid amount',
  'paid for': 'Paid for',
  'partial paid': 'Paid partially',
  partialpaid: 'Paid partially',
  'partner token': 'Security token of partner',
  password: 'Password',
  passwords_not_equal: 'Password does not coincide',
  passwordvalidationmessage:
    'Password must contain uppercase letters, lowercase letters, figures and symbols with a minimum length of 6 characters',
  patient: 'Patient',
  'patient first name': 'Name of patient',
  'patient full name': 'Full name of patient',
  'patient last name': 'Surname of patient',
  'patient name': 'Name of patient',
  patientname: 'Name of patient',
  patient_not_found: 'The patient was not found',
  patient_not_on_site: 'The patient is not in the clinic!',
  'patient phone': 'Telephone of patient',
  patientphone: 'Telephone of patient',
  patients: 'Patients',
  patients_import_note:
    'Note: Patients without phone number will not be imported.',
  patient_source: 'Source of patient',
  'patients per page': 'Patients per page',
  'patients statistics': 'Statistics of patients',
  patient_tags: 'Tags',
  pause: 'Pause',
  pay: 'Pay',
  payinvoice: 'Registered a payment',
  payment_address1: 'Primary address',
  payment_address2: 'Secondary address',
  payment_card_holder: 'Card Holder',
  payment_card_number: 'Card Number',
  payment_city: 'City',
  payment_country: 'Country',
  payment_due: 'Payment due',
  payment_frequency: 'How often do you want to pay?',
  payment_info:
    'You will be charged today {1} for {2} seat(s), in total you will have available {3} seat(s)',
  payment_info_address: 'Invoicing address',
  payment_info_card: 'Payment Card Details',
  payment_info_no_payment:
    'At the completion of the registration, no payment will be charged categorically',
  payment_method: 'Payment method',
  payment_mm: 'MM',
  payment_removal: 'Remove {1} seat(s), remaining with only {2} seat(s)',
  payments: 'Payments',
  payment_state: 'County/District',
  payment_title: 'Payments',
  payment_valid_till: 'Valid until',
  payment_yy: 'YY',
  payment_zip: 'Postal Code',
  pending: 'Scheduled',
  'pending delivery': 'Pending delivery',
  'pending payment': 'Pending',
  pendingpayment: 'Pending',
  period: 'Period',
  'personal info': 'Details on patient',
  persons: 'persons',
  phone: 'Telephone',
  phonecall: 'Telephone call',
  phone_invalid_message: 'Telephone number is invalid.',
  'phone number': 'Telephone number',
  phonenumber: 'Telephone number',
  'phone records': 'Phone records',
  photo: 'Photo',
  previous: 'Back',
  price: 'Price',
  priceatexecutiontime: 'Initial price',
  priceatpaymenttime: 'Price at payment',
  'print plan': 'Print plan',
  'print receipt': 'Print receipt',
  promotionalmessage: 'Promotional message',
  promotionalmessagedesc:
    'This message will be sent to all patients once on the date selected below',
  prosthetics: 'Prostheses',
  'provided services': 'Offered services',
  radiograph: 'Radiography',
  'received by': 'Collected by',
  receiverphone: 'Telephone number',
  receivers: 'Recipients',
  'receivers filter': 'Recipients filter',
  reception: 'Receptionist',
  receptionist: 'Receptionist',
  receptionists: 'Reception',
  'redirecting to clinic': 'We redirect you to clinic',
  'register payment': 'Register payment',
  remained: 'Remained',
  reminder_updated: 'Modified task',
  removal_date_notice: 'Modifications will enter into force since {1}',
  remove_notice:
    'In your clinic {1} doctor(s) for whom you must have seats are registered.',
  remove_seats: 'Remove seats',
  'rename column': 'Rename column',
  required: 'Mandatory',
  'required time': 'Duration',
  rescheduled: 'Rescheduled',
  reset: 'Reset',
  'reset password': 'Reset password',
  'reset password message':
    'Enter email address associated with your account and we will send you a link to reset your password.',
  reset_password_message:
    'Enter email address associated with your account and we will send you a link to reset your password.',
  responsible: 'Responsible',
  restore: 'Restore',
  'restore service': 'Recovery of service',
  retry_payment: 'Retry payment',
  'role for user': 'Role of user in clinic',
  'rows per page': 'Rows per page',
  saturday: 'Saturday',
  save: 'Save',
  'saved successfully': 'Data were saved successfully!',
  schedule_already_paid: 'Appointment was already paid!',
  'schedule date': 'Date of appointment',
  'schedule hour': 'Hour of appointment',
  'schedule info not found': 'Information on appointment was not found',
  schedule_not_found: 'Appointment was not found',
  schedulenotification: 'Notification about appointment',
  schedulenotificationdesc:
    'This message will be sent to the patients the day before the appointment.',
  schedules: 'Appointments',
  'schedules statistics': 'Statistics of appointments',
  'schedules stats': 'Status of appointments',
  'schedule time': 'Hour of appointment',
  'Schedule was deleted': 'Appointment was deleted!',
  search: 'Search',
  searching: 'Searching',
  'search patient': 'Search for patient',
  seats: 'Seat(s)',
  seats_available: 'Available seat(s)',
  'security settings': 'Security settings',
  'select a clinic': 'Select a clinic',
  'select a page': 'Select a page',
  'select category': 'Select a category',
  'select color': 'Select a colour',
  'select doctor': 'Select doctor',
  'select doctor from the list': 'Select doctors from list',
  selected_doctor_does_not_provide_this_service:
    'The selected doctor does not provide this service',
  selected_file_is_not_an_image: 'The selected file is not an image',
  'select patient': 'Select patient',
  'select phase': 'Select stage',
  'select teeth for': 'Select teeth for',
  'select type of data to import': 'Select which data you want to import',
  send: 'Send',
  'send message': 'Send message',
  'send notification at': 'Hour of message sending',
  sendsmsaction: 'Sent a sms',
  sendstatus: 'Status',
  'send time': 'Hour of sending',
  'sent by': 'Sent by',
  sentby: 'Sent by',
  service: 'Service',
  service_already_exists_on_schedule:
    'This service already exists for the given appointment.',
  'service information': 'Details on service',
  'service name': 'Service name',
  servicename: 'Service name',
  service_not_provided_by_user: 'Service is not provided by doctor',
  'service price': 'Price',
  services: 'Services',
  'services statistics': 'Statistics of services',
  'service type': 'Type of service',
  set_as_default: 'Set default card',
  settings: 'Settings',
  setting_tags_current: 'Current tags',
  setting_tags_field: 'Add tag',
  setting_tags_helper: 'Enter tag name and press Enter to add',
  setting_tags_share_all: 'Share all tags',
  share_tags_success: 'Tags were shared with clinic {1}',
  show_doctor_on_confirmation:
    'Display name of doctor on the appointment confirmation page',
  'show in calendar': 'Show in calendar',
  'sign up': 'Create account',
  something_went_wrong: 'Ooops, something went wrong!',
  source: 'Source',
  spoken_language: 'Spoken language',
  spokenlanguage: 'Spoken language',
  start_migration_message:
    'By clicking on the START button we will import all data from Yclients into EasyPlan. This process may take some time, you can continue to explore the application and we will notify you when everything is ready.',
  'start time': 'Beginning',
  status: 'Status',
  statuses: 'Statuses',
  'step 1': 'Step 1.',
  'step 2': 'Step 2.',
  'step 3': 'Step 3.',
  'step 4': 'Step 4.',
  sunday: 'Sunday',
  surgery: 'Surgical intervention',
  switchclinic: 'Changed clinic',
  switch_month_plan: 'Switch to monthly plan',
  switch_year_plan: 'Switch to annual plan and save',
  tax_prorated_info:
    'New seat at price of {1} / month each, calculated proportionally for {2} days',
  tech_support: 'Technical assistance',
  this_cabinet_has_no_doctors: 'There are no doctors in this office',
  'this month': 'Current month',
  'this week': 'Current week',
  thursday: 'Thursday',
  time: 'Time',
  'time before schedule': 'Time before appointment',
  'time zone': 'Time zone',
  title: 'Title',
  to: 'to',
  today: 'Today',
  tooth: 'Tooth {1}',
  toothid: 'Tooth',
  totalamount: 'Total amount',
  'total income': 'Total income',
  transaction_unsuccessful: 'Failed transaction',
  treatment: 'Treatment',
  'treatment plan': 'Treatment plan',
  'treatment type': 'Treatment type',
  tuesday: 'Tuesday',
  type_here: 'Type here',
  'type to search': 'Type to search',
  type_to_search: 'Type to search for…',
  undo_payment: 'Cancel payment',
  undo_payment_confirm_message:
    'All payments for the same invoice will be cancelled. Are you sure you want to cancel the payment?',
  unknown: 'Unknown',
  'unknown delivery status': 'Unknown status',
  'unmapped items will not be imported':
    'Unshared elements will not be imported',
  update: 'Update',
  updatebracesplanaction: 'Orthodontic plan was modified',
  updatedorthodonticplan: 'Treatment plan was edited',
  updateinvoiceaction: 'An invoice was modified',
  updateinvoiceserviceaction: 'A service in invoice was modified',
  updatenoteaction: 'Edited a note',
  updatepatientaction: 'Modified patient',
  updateplanserviceaction: 'Modified a service in treatment plan',
  updatescheduleaction: 'Modified an appointment',
  'upload csv file': 'Upload CSV file',
  'upload file': 'Select file (.xls, .xlsx)',
  'upload image': 'Select image',
  user: 'User',
  username: 'User name',
  user_not_found: 'User was not found',
  users: 'Users',
  value: 'Value',
  'value in easyplan': 'Value in EasyPlan',
  'value in your file': 'Value in file',
  value_less_then: 'Value must be less than',
  value_more_then: 'Value must be greater than',
  version: 'Version',
  view: 'Details',
  viewactivitylogs: 'Viewed activity log',
  viewappointment: 'Viewed an appointment',
  viewappointments: 'Viewed appointments',
  viewcategory: 'Viewed a category',
  'view debt': 'View debt',
  'view details': 'Details',
  viewdoctorsstatistics: 'Viewed statistics of doctors',
  viewgeneralstatistics: 'Viewed general statistics',
  view_more: 'View all',
  viewpatient: 'Viewed a patient',
  viewpatients: 'Viewed all patients',
  viewservice: 'Viewed a service',
  viewservices: 'Viewed all services',
  viewservicesstatistics: 'Viewed statistics of services',
  viewuser: 'Viewed a user',
  viewusers: 'Viewed all users',
  visible_states: 'Visible statuses',
  visitdate: 'Date of visit',
  visits: 'Visits',
  waiting: 'Waiting',
  'waiting for patient': 'Waiting for patient',
  waitingforpatient: 'Waiting for patient',
  'we are ready to start': 'We are ready for data migration',
  wednesday: 'Wednesday',
  week: 'Week',
  'week schedules': 'Appointments for a week',
  'welcome to easyplan': 'Welcome to EasyPlan',
  'why schedule is canceled': 'Why appointment was cancelled',
  'work hours': 'Work schedule',
  'working hours': 'Working hours',
  wrong_username_or_password: 'Wrong email or password',
  yclients_auth_explanation:
    'In order to be able to import data from Yclients into EasyPlan, we need access to your Yclients account.',
  year: 'Year',
  yearly: 'Annually',
  yes: 'Yes',
  yesterday: 'Yesterday',
  employer_certificate: 'Certificat angajator',
  address: 'Adresa',
  identity_card: 'Carte de identitate',
  series: 'Serie',
  idnp: 'IDNP',
  add_comment: 'Add a comment',
  no_comment_label: 'This call has no comments',
};
