export default Object.freeze({
  updateCategories: false,
  updateServices: false,
  updateUsers: false,
  updateXRay: false,
  updateNotes: false,
  updateCurrentUser: false,
  newClinicId: null,
  logout: false,
  user: null,
  updateAppointments: false,
  updateCalendarDoctorHeight: false,
  checkAppointments: false,
  updateInvoices: false,
  checkDoctorAppointments: false,
  patientDetails: { show: false, patientId: null, onDelete: null },
  updatePatients: false,
  updatePatientPayments: false,
});
