export default {
  updateCategories: false,
  updateUsers: false,
  updateXRay: false,
  updateNotes: false,
  updateCurrentUser: false,
  newClinicId: null,
  logout: false,
  user: null,
  createClinic: { open: false, canClose: false },
  patientNoteModal: {
    open: false,
    patientId: null,
    mode: 'notes',
    scheduleId: null,
  },
  patientXRayModal: { open: false, patientId: null },
  appointmentModal: { open: false, date: null, doctor: null, schedule: null },
  updateAppointments: false,
};
