export default {
  en: {
    analytics: 'Analytics',
    categories: 'Categories',
    users: 'Users',
    calendar: 'Calendar',
    patients: 'Patients',
    settings: 'Settings',
    close: 'Close',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    confirm: 'Confirm',
    search: 'Search',
    list: 'List',
    'delete category': 'Delete category',
    'edit category': 'Edit category',
    'add category': 'Add category',
    'enter category name': 'Enter category name',
    'are you sure you want to delete this category?':
      'Are you sure you want to delete this category?',
    services: 'Services',
    'add service': 'Add service',
    'edit service': 'Edit service',
    'delete service': 'Delete service',
    'are you sure you want to delete this service?':
      'Are you sure you want to delete this service?',
    'service information': 'Service information',
    'step 1.': 'Step 1.',
    'step 2.': 'Step 2.',
    'step 3.': 'Step 3.',
    'step 4.': 'Step 4.',
    'service name': 'Service name',
    'required time': 'Required time',
    'service price': 'Service price',
    'select color': 'Select color',
    administrators: 'Administrators',
    receptionists: 'Receptionists',
    doctors: 'Doctors',
    all: 'All',
    'add new user': 'Add new user',
    'add one +': 'Add one +',
    'no phone number': 'No phone number',
    'no managers yet.': 'No managers yet.',
    'no doctors yet.': 'No doctors yet.',
    'no receptionists yet.': 'No receptionists yet.',
    'add manager': 'Add manager',
    'add doctor': 'Add doctor',
    'add receptionist': 'Add receptionist',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    'add holiday': 'Add holiday',
    'no description': 'No description',
    'day off': 'Day off',
    'chose...': 'Chose...',
    to: 'to',
    holidays: 'Holidays',
    'work hours': 'Work hours',
    'provided services': 'Provided services',
    'account information': 'Account information',
    'upload image': 'Upload image',
    'first name': 'First name',
    'last name': 'Last name',
    email: 'Email',
    'phone number': 'Phone number',
    'jpg or png, max size of 800kb': 'JPG or PNG, Max size of 800kb',
    'add user': 'Add user',
    'edit user': 'Edit user',
    time: 'Time',
    price: 'Price',
    description: 'Description',
    'doctors who provide this service': 'Doctors who provide this service',
    manager: 'Manager',
    receptionist: 'Receptionist',
    doctor: 'Doctor',
    'delete user': 'Delete user',
    'are you sure you want to delete this user?':
      'Are you sure you want to delete this user?',
    day: 'Day',
    week: 'Week',
    month: 'Month',
    year: 'Year',
    'created by': 'created by',
    'all services': 'All services',
    'add appointment': 'Add appointment',
    'reset password message':
      "Enter the email address associated with your account and we'll send you a link to reset your password.",
    password: 'Password',
    wrong_username_or_password: 'Wrong email or password',
    'logout message': 'Are you sure you want to log out from your account?',
    logout: 'Logout',
    'company details': 'Company details',
    'working hours': 'Working hours',
    'account settings': 'Account settings',
    'security settings': 'Security settings',
    'current password': 'Current password',
    'new password': 'New password',
    'confirm new password': 'Confirm new password',
    waiting: 'Waiting',
    'did not come': 'Did not come',
    finished: 'Finished',
    confirmed: 'Confirmed',
    paid: 'Paid',
    date: 'Date',
    period: 'Period',
    patient: 'Patient',
    service: 'Service',
    status: 'Status',
    'all doctors': 'All doctors',
    'all statuses': 'All statuses',
    'apply filters': 'Apply filters',
    'services statistics': 'Services statistics',
    'doctors statistics': 'Doctors statistics',
    'activity logs': 'Activity logs',
    general: 'General',
    'general statistics': 'General statistics',
    'accept invitation message':
      'Create a password that will be used to login to your account.',
    'treatment plan': 'Treatment plan',
    diagnosis: 'Diagnosis',
    radiograph: 'Radiograph',
    occlusion: 'Occlusion',
    included: 'Included',
    'fallen brackets': 'Fallen brackets',
    'appointments notes': 'Appointments notes',
    'add note': 'Add note',
    'initial phase': 'Initial phase',
    'middle phase': 'Middle phase',
    'final phase': 'Final phase',
    'select phase': 'Select phase',
    'add image': 'Add image',
    'no selected services': 'No selected services',
    finalize: 'Finalize',
    notes: 'Notes',
    'patient name': 'Patient name',
    'existent patient': 'Existent patient',
    'new patient': 'New patient',
    'no available time': 'No available time',
    pending: 'Pending',
    late: 'Late',
    canceled: 'Canceled',
    'on site': 'On site',
    'waiting for patient': 'Waiting for patient',
    'completed not paid': 'Completed not paid',
    'partial paid': 'Partial paid',
    'type to search': 'Type to search',
    'enter doctor name or phone': 'Enter doctor name or phone',
    'enter patient name or phone': 'Enter patient name or phone',
    'enter service name': 'Enter service name',
    searching: 'Searching',
    'no results': 'No results found',
    'delete appointment': 'Delete appointment',
    'delete appointment message':
      'Are you sure you want to delete this appointment?',
    'for payment': 'For payment',
    'patients statistics': 'Patients statistics',
    'no appointment': 'No appointment',
    view: 'View',
    'appointment status': 'Appointment status',
    'treatment type': 'Treatment type',
    'service type': 'Service type',
    note: 'Notes',
    'no treatment plan': 'No treatment plan',
    'create new password': 'Create new password',
    'change password message': 'Password must contain at leas 8 characters',
    'enter a new password': 'Introduce o parolă nouă',
    'confirm password': 'Confirmă parola nouă',
    'accept invitation': 'Accept invitation',
    'create new account': 'Create new account',
    persons: 'persons',
    partialpaid: 'Partial paid',
    completednotpaid: 'Completed not paid',
    completedpaid: 'Completed paid',
    'total incom': 'Total income',
    'doctor part': 'Doctor salary',
    'clinic profit': 'Clinic profit',
    today: 'Today',
    yesterday: 'Yesterday',
    'this week': 'This week',
    'last week': 'Last week',
    'this month': 'This month',
    'last month': 'Last month',
    'days up to today': 'Days up to today',
    'days starting today': 'Days starting today',
    user: 'User',
    details: 'Details',
    'all users': 'All users',
    createcategory: 'A creat o categorie',
    editcategory: 'A editat o categorie',
    deletecategory: 'A șters o categorie',
    viewcategory: 'A vizualizat o categorie',
    createservice: 'A creat un serviciu',
    editservice: 'A editat un serviciu',
    deleteservice: 'A șters un serviciu',
    viewservice: 'A vizualizat un serviciu',
    viewservices: 'A vizualizat toate serviciile',
    createappointment: 'A creat o programare',
    editappointment: 'A editat o programare',
    deleteappointment: 'A șters o programare',
    viewappointment: 'A vizualizat o programare',
    viewappointments: 'A vizualizat programările',
    createpatient: 'A creat un pacient',
    editpatient: 'A editat un pacient',
    deletepatient: 'A șters un pacient',
    viewpatient: 'A vizualizat un pacient',
    viewpatients: 'A vizualizat toți pacienții',
    createClinic: 'A creat o clinică',
    editclinic: 'A editat clinica',
    payinvoice: 'A înregistrat o achitare',
    finalizetreatment: 'A finisat un tratament',
    viewgeneralstatistics: 'A vizualizat statistica generală',
    viewservicesstatistics: 'A vizualizat statistica serviciilor',
    viewdoctorsstatistics: 'A vizualizat statistica doctorilor',
    viewactivitylogs: 'A vizualizat jurnalul activităților',
    switchclinic: 'A schimbat clinica',
    createuser: 'A creat un utilizator',
    edituser: 'A editat un utilizator',
    viewuser: 'A vizualizat un utilizator',
    viewusers: 'A vizualizat toți utilizatorii',
    deleteuser: 'A șters un utilizator',
    createpatientnote: 'A adaugat o notă la un pacient',
    addpatientxrayimage: 'A adăugat o imagine X-Ray la un pacient',
    updatedorthodonticplan: 'A editat planul de tratament',
    editvisitnote: 'A editat nota la o vizită',
    'view details': 'View details',
    hour: 'Hour',
    phone: 'Phone',
    debts: 'Debts',
    'no debts found': 'No debts found',
    pay: 'Pay',
    remained: 'Remained',
    actions: 'Actions',
    name: 'Name',
    braces: 'Braces',
    malocclusion: 'Malocclusion',
    mandible: 'Mandible',
    maxillary: 'Maxillary',
    "it's a day off": "It's a day off",
    'apply to all': 'Apply to all',
    liabilities: 'Liabilities',
    'did not came': 'Did not came',
    expectations: 'Expectations',
    'created at': 'Created at',
    'orthodontic plan': 'Orthodontic plan',
    'offers braces services': 'Offers Braces services',
    'application settings': 'Application settings',
    'animate appointments before': 'Animate appointments before',
    appointment_animation_timer:
      'Indicate the amount of time that a schedule should be animated before its time',
    'app initialization': 'App initialization',
    'create clinic': 'Create clinic',
    'loading statistics': 'Loading statistics',
    'clinic name': 'Clinic name',
    'about clinic': 'About clinic',
    optional: 'Optional',
    currency: 'Currency',
    country: 'Country',
    update: 'Update',
    apply: 'Apply',
    'forgot your password': 'Forgot your password',
    "don't have an account": "Don't have an account",
    'sign up': 'Sign Up',
    'welcome to easyplan': 'Welcome to EasyPlan',
    'log in to your account': 'Log in to your account',
    'already have an account': 'Already have an account',
    'reset password': 'Reset password',
    reset_password_message:
      "Enter the email address associated with your account and we'll send you a link to reset your password.",
    'go back': 'Go back',
    birthday: 'Birthday',
    invite: 'Invite',
    'invitation sent': 'Invitation sent',
    invitation_sent_message: 'A new invitation email was sent to this user.',
    'invite existent user': 'Invite existent user',
    reception: 'Reception',
    'role for user': 'Role for user',
    user_not_found: 'User not found',
    'delete clinic': 'Delete clinic',
    delete_clinic_message: 'Are you sure you want to delete current clinic?',
  },
  ro: {
    analytics: 'Analitică',
    categories: 'Categorii',
    users: 'Utilizatori',
    calendar: 'Calendar',
    patients: 'Pacienți',
    settings: 'Setări',
    close: 'Închide',
    cancel: 'Amână',
    save: 'Salvează',
    delete: 'Șterge',
    edit: 'Editează',
    confirm: 'Confirmă',
    search: 'Caută',
    list: 'Lista',
    'delete category': 'Șterge categorie',
    'edit category': 'Editează categorie',
    'add category': 'Adaugă categorie',
    'enter category name': 'Introduceți denumirea categoriei',
    'are you sure you want to delete this category?':
      'Sunteți sigur(ă) că doriți să ștergeți această categorie?',
    services: 'Servicii',
    'add service': 'Adaugă serviciu',
    'edit service': 'Editează serviciu',
    'delete service': 'Șterge serviciu',
    'are you sure you want to delete this service?':
      'Sunteți sigur(ă) că doriți să ștergeți aceast serviciu?',
    'service information': 'Detalii serviciu',
    'step 1.': 'Pasul 1.',
    'step 2.': 'Pasul 2.',
    'step 3.': 'Pasul 3.',
    'step 4.': 'Pasul 4.',
    'service name': 'Denumire serviciu',
    'required time': 'Durata',
    'service price': 'Prețul',
    'select color': 'Alege o culoare',
    administrators: 'Manageri',
    receptionists: 'Recepție',
    doctors: 'Doctori',
    all: 'Toți',
    'add new user': 'Adaugă utilizator',
    'add one +': 'Adaugă +',
    'no phone number': 'Nu este indicat',
    'no managers yet.': 'Nu este nici un manager încă.',
    'no doctors yet.': 'Nu este nici un doctor încă.',
    'no receptionists yet.': 'Nu este nici un recepționist încă.',
    'add manager': 'Adaugă manager',
    'add doctor': 'Adaugă doctor',
    'add receptionist': 'Adaugă recepționist',
    monday: 'Luni',
    tuesday: 'Marți',
    wednesday: 'Miercuri',
    thursday: 'Joi',
    friday: 'Vineri',
    saturday: 'Sâmbătă',
    sunday: 'Duminică',
    'add holiday': 'Adaugă vacanță',
    'no description': 'Nu este descriere',
    'day off': 'Zi liberă',
    'chose...': 'Alege...',
    to: 'pînă la',
    holidays: 'Vacanțe',
    'work hours': 'Orarul de lucru',
    'provided services': 'Serviciile oferite',
    'account information': 'Detalii cont',
    'upload image': 'Alege imagine',
    'first name': 'Prenume',
    'last name': 'Nume',
    email: 'Email',
    'phone number': 'Număr de telefon',
    'jpg or png, max size of 800kb': 'JPG or PNG, Mărime maximă 800kb',
    'add user': 'Adaugă utilizator',
    'edit user': 'Editează utilizator',
    time: 'Timp',
    price: 'Preț',
    description: 'Descriere',
    'doctors who provide this service': 'Doctori care oferă acest serviciu',
    manager: 'Manager',
    receptionist: 'Recepționist',
    doctor: 'Doctor',
    'delete user': 'Șterge utilizator',
    'are you sure you want to delete this user?':
      'Sunteți sigur(ă) că vreți sa ștergeți acest utilizator?',
    day: 'Zi',
    week: 'Săptămână',
    month: 'Lună',
    year: 'An',
    'created by': 'creat de',
    'all services': 'Toate serviciile',
    'add appointment': 'Adaugă programare',
    'reset password message':
      "Enter the email address associated with your account and we'll send you a link to reset your password.",
    password: 'Parola',
    wrong_username_or_password: 'Wrong email or password',
    'logout message': 'Sunteți sigur(ă) că doriți să va delogați?',
    logout: 'Delogare',
    'company details': 'Detalii companie',
    'working hours': 'Program de lucru',
    'account settings': 'Setări cont',
    'security settings': 'Setări de securitate',
    'current password': 'Parola curentă',
    'new password': 'Parola nouă',
    'confirm new password': 'Confirmați parola nouă',
    waiting: 'În așteptare',
    'did not come': 'Nu a venit',
    finished: 'Finisat',
    confirmed: 'Confirmat',
    paid: 'Achitat',
    date: 'Data',
    period: 'Perioada',
    patient: 'Pacient',
    service: 'Serviciu',
    status: 'Statut',
    'all doctors': 'Toți doctorii',
    'all statuses': 'Toate statuturile',
    'apply filters': 'Aplică filtrele',
    'services statistics': 'Statistica serviciilor',
    'doctors statistics': 'Statistica doctorilor',
    'activity logs': 'Jurnal activități',
    general: 'General',
    'general statistics': 'Statistica generală',
    'accept invitation message':
      'Create a password that will be used to login to your account.',
    'treatment plan': 'Plan de tratament',
    diagnosis: 'Diagnostică',
    radiograph: 'Radiografie',
    occlusion: 'Ocluzie',
    included: 'Inclus',
    'fallen brackets': 'Brackeți căzuți',
    'appointments notes': 'Vizite',
    'add note': 'Adaugă notă',
    'initial phase': 'Faza inițială',
    'middle phase': 'Faza mijlocie',
    'final phase': 'Faza finală',
    'select phase': 'Alege faza',
    'add image': 'Adaugă imagine',
    'no selected services': 'Nu sunt servicii selectate',
    finalize: 'Finalizează',
    notes: 'Notițe',
    'patient name': 'Nume pacient',
    'existent patient': 'Pacient existent',
    'new patient': 'Pacient nou',
    'no available time': 'Nu este timp liber',
    pending: 'Programat',
    late: 'Întârzie',
    canceled: 'Anulat',
    'on site': 'Pe loc',
    'waiting for patient': 'În așteptare pacient',
    'completed not paid': 'Finisat ne achitat',
    'partial paid': 'Achitat parțial',
    'type to search': 'Tapează pentru a căuta',
    'enter doctor name or phone': 'Introduceți numele sau numărul de telefon',
    'enter patient name or phone': 'Introduceți numele sau numărul de telefon',
    'enter service name': 'Introduceți numele serviciului',
    searching: 'Căutăm',
    'no results': 'Nu au fost găsite rezultate',
    'delete appointment': 'Șterge programare',
    'delete appointment message':
      'Sunteți sigur(ă) că doriți să ștergeți această programare?',
    'for payment': 'Spre achitare',
    'patients statistics': 'Statistica pacienților',
    'no appointment': 'Nu are programare',
    view: 'Detalii',
    'appointment status': 'Statutul programării',
    'treatment type': 'Tip tratament',
    'service type': 'Tip serviciu',
    note: 'Notițe',
    'no treatment plan': 'Nu are plan de tratament',
    'create new password': 'Creează parola nouă',
    'change password message': 'Parola trebuie sa conțină minim 8 caractere.',
    'enter a new password': 'Introduce o parolă nouă',
    'confirm password': 'Confirmă parola nouă',
    'accept invitation': 'Acceptă invitația',
    'create new account': 'Creează cont',
    persons: 'persoane',
    partialpaid: 'Achitat parțial',
    completednotpaid: 'Finisat ne achitat',
    completedpaid: 'Achitat',
    'total incom': 'Venit total',
    'doctor part': 'Salariul doctorului',
    'clinic profit': 'Profitul clinicii',
    today: 'Astăzi',
    yesterday: 'Ieri',
    'this week': 'Săptămâna curentă',
    'last week': 'Săptămâna trecută',
    'this month': 'Luna curentă',
    'last month': 'Luna trecută',
    'days up to today': 'zile până astăzi',
    'days starting today': 'zile de astăzi',
    user: 'Utilizator',
    details: 'Detalii',
    'all users': 'Toți utilizatorii',
    createcategory: 'A creat o categorie',
    editcategory: 'A editat o categorie',
    deletecategory: 'A șters o categorie',
    viewcategory: 'A vizualizat o categorie',
    createservice: 'A creat un serviciu',
    editservice: 'A editat un serviciu',
    deleteservice: 'A șters un serviciu',
    viewservice: 'A vizualizat un serviciu',
    viewservices: 'A vizualizat toate serviciile',
    createappointment: 'A creat o programare',
    editappointment: 'A editat o programare',
    deleteappointment: 'A șters o programare',
    viewappointment: 'A vizualizat o programare',
    viewappointments: 'A vizualizat programările',
    createpatient: 'A creat un pacient',
    editpatient: 'A editat un pacient',
    deletepatient: 'A șters un pacient',
    viewpatient: 'A vizualizat un pacient',
    viewpatients: 'A vizualizat toți pacienții',
    createClinic: 'A creat o clinică',
    editclinic: 'A editat clinica',
    payinvoice: 'A înregistrat o achitare',
    finalizetreatment: 'A finisat un tratament',
    viewgeneralstatistics: 'A vizualizat statistica generală',
    viewservicesstatistics: 'A vizualizat statistica serviciilor',
    viewdoctorsstatistics: 'A vizualizat statistica doctorilor',
    viewactivitylogs: 'A vizualizat jurnalul activităților',
    switchclinic: 'A schimbat clinica',
    createuser: 'A creat un utilizator',
    edituser: 'A editat un utilizator',
    viewuser: 'A vizualizat un utilizator',
    viewusers: 'A vizualizat toți utilizatorii',
    deleteuser: 'A șters un utilizator',
    createpatientnote: 'A adaugat o notă la un pacient',
    addpatientxrayimage: 'A adăugat o imagine X-Ray la un pacient',
    updatedorthodonticplan: 'A editat planul de tratament',
    editvisitnote: 'A editat nota la o vizită',
    'view details': 'Detalii',
    hour: 'Ora',
    phone: 'Telefon',
    debts: 'Datorii',
    'no debts found': 'Nu are datorii',
    pay: 'Achită',
    remained: 'Rămas',
    actions: 'Acțiuni',
    name: 'Nume',
    braces: 'Aparat dentar',
    malocclusion: 'Malocluzie',
    mandible: 'Mandibulă',
    maxillary: 'Maxilar',
    "it's a day off": 'Este zi liberă',
    'apply to all': 'Aplică la toate',
    liabilities: 'Datorii',
    'did not came': 'Nu au venit',
    expectations: 'Programați',
    'created at': 'Creat la data',
    'orthodontic plan': 'Plan ortodontic',
    'offers braces services': 'Oferă servicii ortodontice',
    'application settings': 'Setări aplicație',
    'animate appointments before': 'Notifică despre programare din timp',
    appointment_animation_timer:
      'Indică cu cât timp înainte trebuie animate programările',
    'app initialization': 'Inițializarea aplicației',
    'create clinic': 'Crează clinică',
    'loading statistics': 'Se încarcă statistica',
    'clinic name': 'Denumire clinică',
    'about clinic': 'Despre clinică',
    optional: 'Opțional',
    currency: 'Valută',
    country: 'Țara',
    update: 'Înoiește',
    apply: 'Aplică',
    'forgot your password': 'Ai uitat parola',
    "don't have an account": 'Nu ai un cont',
    'sign up': 'Crează cont',
    'welcome to easyplan': 'Bun venit în EasyPlan',
    'log in to your account': 'Conectează-te la contul tău',
    'already have an account': 'Deja am un cont',
    'reset password': 'Resetează parola',
    reset_password_message:
      'Introduce adresa de email asociată cu contul tău și noi îți vom trimite un link pentru resetare.',
    'go back': 'Înapoi',
    birthday: 'Data nașterii',
    invite: 'Invită',
    'invitation sent': 'Invitație transmisă',
    invitation_sent_message:
      'Un email nou cu invitație în clinica Dvs a fost transmis.',
    'invite existent user': 'Invită utilizator existent',
    reception: 'Recepționist',
    'role for user': 'Rolul utilizatorului în clinică',
    user_not_found: 'Utilizatorul nu a fost găsit',
    'delete clinic': 'Șterge clinică',
    delete_clinic_message:
      'Sunteți sigur că doriți să ștergeți clinica curentă?',
  },
  ru: {
    analytics: 'Analytics',
    categories: 'Categories',
    users: 'Users',
    calendar: 'Calendar',
    patients: 'Patients',
    settings: 'Settings',
    close: 'Close',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    confirm: 'Confirm',
    search: 'Search',
    list: 'List',
    'delete category': 'Delete category',
    'edit category': 'Edit category',
    'add category': 'Add category',
    'enter category name': 'Enter category name',
    'are you sure you want to delete this category?':
      'Are you sure you want to delete this category?',
    services: 'Services',
    'add service': 'Add service',
    'edit service': 'Edit service',
    'delete service': 'Delete service',
    'are you sure you want to delete this service?':
      'Are you sure you want to delete this service?',
    'service information': 'Service information',
    'step 1.': 'Step 1.',
    'step 2.': 'Step 2.',
    'step 3.': 'Step 3.',
    'step 4.': 'Step 4.',
    'service name': 'Service name',
    'required time': 'Required time',
    'service price': 'Service price',
    'select color': 'Select color',
    administrators: 'Administrators',
    receptionists: 'Receptionists',
    doctors: 'Doctors',
    all: 'All',
    'add new user': 'Add new user',
    'add one +': 'Add one +',
    'no phone number': 'No phone number',
    'no managers yet.': 'No managers yet.',
    'no doctors yet.': 'No doctors yet.',
    'no receptionists yet.': 'No receptionists yet.',
    'add manager': 'Add manager',
    'add doctor': 'Add doctor',
    'add receptionist': 'Add receptionist',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    'add holiday': 'Add holiday',
    'no description': 'No description',
    'day off': 'Day off',
    'chose...': 'Chose...',
    to: 'to',
    holidays: 'Holidays',
    'work hours': 'Work hours',
    'provided services': 'Provided services',
    'account information': 'Account information',
    'upload image': 'Upload image',
    'first name': 'First name',
    'last name': 'Last name',
    email: 'Email',
    'phone number': 'Phone number',
    'jpg or png, max size of 800kb': 'JPG or PNG, Max size of 800kb',
    'add user': 'Add user',
    'edit user': 'Edit user',
    time: 'Time',
    price: 'Price',
    description: 'Description',
    'doctors who provide this service': 'Doctors who provide this service',
    manager: 'Manager',
    receptionist: 'Receptionist',
    doctor: 'Doctor',
    'delete user': 'Delete user',
    'are you sure you want to delete this user?':
      'Are you sure you want to delete this user?',
    day: 'Day',
    week: 'Week',
    month: 'Month',
    year: 'Year',
    'created by': 'created by',
    'all services': 'All services',
    'add appointment': 'Add appointment',
    'reset password message':
      "Enter the email address associated with your account and we'll send you a link to reset your password.",
    password: 'Password',
    wrong_username_or_password: 'Wrong email or password',
    'logout message': 'Are you sure you want to log out from your account?',
    logout: 'Выход',
    'company details': 'Company details',
    'working hours': 'Working hours',
    'account settings': 'Account settings',
    'security settings': 'Security settings',
    'current password': 'Current password',
    'new password': 'New password',
    'confirm new password': 'Confirm new password',
    waiting: 'Waiting',
    'did not come': 'Did not come',
    finished: 'Finished',
    confirmed: 'Confirmed',
    paid: 'Paid',
    date: 'Date',
    period: 'Period',
    patient: 'Patient',
    service: 'Service',
    status: 'Status',
    'all doctors': 'All doctors',
    'all statuses': 'All statuses',
    'apply filters': 'Apply filters',
    'services statistics': 'Statistica serviciilor',
    'doctors statistics': 'Doctors statistics',
    'activity logs': 'Activity logs',
    general: 'General',
    'general statistics': 'General statistics',
    'accept invitation message':
      'Create a password that will be used to login to your account.',
    'treatment plan': 'Treatment plan',
    diagnosis: 'Diagnosis',
    radiograph: 'Radiograph',
    occlusion: 'Occlusion',
    included: 'Included',
    'appointments notes': 'Appointments notes',
    'add note': 'Add note',
    'initial phase': 'Initial phase',
    'middle phase': 'Middle phase',
    'final phase': 'Final phase',
    'select phase': 'Select phase',
    'add image': 'Adaugă imagine',
    'no selected services': 'No selected services',
    finalize: 'Finalize',
    notes: 'Notes',
    'patient name': 'Nume pacient',
    'existent patient': 'Pacient existent',
    'new patient': 'Pacient nou',
    'no available time': 'No available time',
    pending: 'Pending',
    late: 'Late',
    canceled: 'Canceled',
    'on site': 'On site',
    'waiting for patient': 'Waiting for patient',
    'completed not paid': 'Completed not paid',
    'partial paid': 'Partial paid',
    'type to search': 'Tapează pentru a căuta',
    'enter doctor name or phone': 'Introduceți numele sau numărul de telefon',
    'enter patient name or phone': 'Introduceți numele sau numărul de telefon',
    'enter service name': 'Introduceți numele serviciului',
    searching: 'Căutăm',
    'no results': 'Nu au fost găsite rezultate',
    'delete appointment': 'Delete appointment',
    'delete appointment message':
      'Are you sure you want to delete this appointment?',
    'for payment': 'For payment',
    'patients statistics': 'Statistica pacienților',
    'no appointment': 'No appointment',
    view: 'View',
    'appointment status': 'Appointment status',
    'treatment type': 'Treatment type',
    'service type': 'Service type',
    note: 'Notes',
    'no treatment plan': 'No treatment plan',
    'create new password': 'Create new password',
    'change password message': 'Password must contain at leas 8 characters',
    'enter a new password': 'Introduce o parolă nouă',
    'confirm password': 'Confirmă parola nouă',
    'accept invitation': 'Accept invitation',
    'create new account': 'Create new account',
    persons: 'persons',
    partialpaid: 'Partial paid',
    completednotpaid: 'Completed not paid',
    completedpaid: 'Completed paid',
    'total incom': 'Total income',
    'doctor part': 'Doctor salary',
    'clinic profit': 'Clinic profit',
    today: 'Today',
    yesterday: 'Yesterday',
    'this week': 'This week',
    'last week': 'Last week',
    'this month': 'This month',
    'last month': 'Last month',
    'days up to today': 'Days up to today',
    'days starting today': 'Days starting today',
    user: 'User',
    details: 'Details',
    'all users': 'All users',
    createcategory: 'A creat o categorie',
    editcategory: 'A editat o categorie',
    deletecategory: 'A șters o categorie',
    viewcategory: 'A vizualizat o categorie',
    createservice: 'A creat un serviciu',
    editservice: 'A editat un serviciu',
    deleteservice: 'A șters un serviciu',
    viewservice: 'A vizualizat un serviciu',
    viewservices: 'A vizualizat toate serviciile',
    createappointment: 'A creat o programare',
    editappointment: 'A editat o programare',
    deleteappointment: 'A șters o programare',
    viewappointment: 'A vizualizat o programare',
    viewappointments: 'A vizualizat programările',
    createpatient: 'A creat un pacient',
    editpatient: 'A editat un pacient',
    deletepatient: 'A șters un pacient',
    viewpatient: 'A vizualizat un pacient',
    viewpatients: 'A vizualizat toți pacienții',
    createclinic: 'A creat o clinică',
    editclinic: 'A editat clinica',
    payinvoice: 'A înregistrat o achitare',
    finalizetreatment: 'A finisat un tratament',
    viewgeneralstatistics: 'A vizualizat statistica generală',
    viewservicesstatistics: 'A vizualizat statistica serviciilor',
    viewdoctorsstatistics: 'A vizualizat statistica doctorilor',
    viewactivitylogs: 'A vizualizat jurnalul activităților',
    switchclinic: 'A schimbat clinica',
    createuser: 'A creat un utilizator',
    edituser: 'A editat un utilizator',
    viewuser: 'A vizualizat un utilizator',
    viewusers: 'A vizualizat toți utilizatorii',
    deleteuser: 'A șters un utilizator',
    createpatientnote: 'A adaugat o notă la un pacient',
    addpatientxrayimage: 'A adăugat o imagine X-Ray la un pacient',
    updatedorthodonticplan: 'A editat planul de tratament',
    editvisitnote: 'A editat nota la o vizită',
    'view details': 'View details',
    hour: 'Hour',
    phone: 'Phone',
    debts: 'Debts',
    'no debts found': 'No debts found',
    pay: 'Pay',
    remained: 'Remained',
    actions: 'Actions',
    name: 'Name',
    braces: 'Braces',
    malocclusion: 'Malocclusion',
    mandible: 'Mandible',
    maxillary: 'Maxillary',
    "it's a day off": "It's a day off",
    'apply to all': 'Apply to all',
    liabilities: 'Liabilities',
    'did not came': 'Did not came',
    expectations: 'Expectations',
    'created at': 'Created at',
    'orthodontic plan': 'Orthodontic plan',
    'offers braces services': 'Offers Braces services',
    'application settings': 'Application settings',
    'animate appointments before': 'Animate appointments before',
    'app initialization': 'App initialization',
    'create clinic': 'Create clinic',
    'loading statistics': 'Loading statistics',
    'clinic name': 'Clinic name',
    'about clinic': 'About clinic',
    optional: 'Optional',
    currency: 'Currency',
    country: 'Country',
    update: 'Update',
    apply: 'Apply',
    'forgot your password': 'Forgot your password',
    "don't have an account": "Don't have an account",
    'sign up': 'Sign Up',
    'welcome to easyplan': 'Welcome to EasyPlan',
    'log in to your account': 'Log in to your account',
    'already have an account': 'Already have an account',
    'reset password': 'Reset password',
    reset_password_message:
      "Enter the email address associated with your account and we'll send you a link to reset your password.",
    'go back': 'Go back',
    birthday: 'Birthday',
    invite: 'Invite',
    'invitation sent': 'Invitation sent',
    invitation_sent_message: 'A new invitation email was sent to this user.',
    'invite existent user': 'Invite existent user',
    reception: 'Reception',
    'role for user': 'Rolul utilizatorului în clinică',
    user_not_found: 'User not found',
    'delete clinic': 'Delete clinic',
    delete_clinic_message: 'Are you sure you want to delete current clinic?',
  },
};
