export default {
  en: {
    analytics: 'Analytics',
    categories: 'Categories',
    users: 'Users',
    calendar: 'Calendar',
    patients: 'Patients',
    settings: 'Settings',
    close: 'Close',
    save: 'Save',
    delete: 'Delete',
    confirm: 'Confirm',
    search: 'Search',
    list: 'List',
    'delete category': 'Delete category',
    'edit category': 'Edit category',
    'add category': 'Add category',
    'enter category name': 'Enter category name',
    'are you sure you want to delete this category?':
      'Are you sure you want to delete this category?',
    services: 'Services',
    'add service': 'Add service',
    'edit service': 'Edit service',
    'delete service': 'Delete service',
    'are you sure you want to delete this service?':
      'Are you sure you want to delete this service?',
    'service information': 'Service information',
    'step 1.': 'Step 1.',
    'step 2.': 'Step 2.',
    'service name': 'Service name',
    'required time': 'Required time',
    'service price': 'Service price',
    'select color': 'Select color',
  },
  ro: {
    analytics: 'Analytics',
    categories: 'Categories',
    users: 'Users',
    calendar: 'Calendar',
    patients: 'Patients',
    settings: 'Settings',
    close: 'Close',
    save: 'Save',
    delete: 'Delete',
    confirm: 'Confirm',
    search: 'Search',
    list: 'List',
    'delete category': 'Delete category',
    'edit category': 'Edit category',
    'add category': 'Add category',
    'enter category name': 'Enter category name',
    'are you sure you want to delete this category?':
      'Are you sure you want to delete this category?',
    services: 'Services',
    'add service': 'Add service',
    'edit service': 'Edit service',
    'delete service': 'Delete service',
    'are you sure you want to delete this service?':
      'Are you sure you want to delete this service?',
    'service information': 'Service information',
    'step 1.': 'Step 1.',
    'step 2.': 'Step 2.',
    'service name': 'Service name',
    'required time': 'Required time',
    'service price': 'Service price',
    'select color': 'Select color',
  },
  ru: {
    analytics: 'Analytics',
    categories: 'Categories',
    users: 'Users',
    calendar: 'Calendar',
    patients: 'Patients',
    settings: 'Settings',
    close: 'Close',
    save: 'Save',
    delete: 'Delete',
    confirm: 'Confirm',
    search: 'Search',
    list: 'List',
    'delete category': 'Delete category',
    'edit category': 'Edit category',
    'add category': 'Add category',
    'enter category name': 'Enter category name',
    'are you sure you want to delete this category?':
      'Are you sure you want to delete this category?',
    services: 'Services',
    'add service': 'Add service',
    'edit service': 'Edit service',
    'delete service': 'Delete service',
    'are you sure you want to delete this service?':
      'Are you sure you want to delete this service?',
    'service information': 'Service information',
    'step 1.': 'Step 1.',
    'step 2.': 'Step 2.',
    'service name': 'Service name',
    'required time': 'Required time',
    'service price': 'Service price',
    'select color': 'Select color',
  },
};
