# This is a basic workflow to help you get started with Actions

name: Deploy Master Admin

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Linux, x64, production]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install all dependencies
        run: yarn install

      - name: Build application
        run: yarn build:production

      - name: Create deploy folder
        run: rm -rf ../deploy && mkdir ../deploy

      - name: Copy .next folder to depoy
        run: cp -a .next/ ../deploy/

      - name: Copy package.json to deploy
        run: cp package.json ../deploy/

      - name: Copy node_modules to deploy
        run: cp -a node_modules/ ../deploy/

      - name: Copy public to deploy
        run: cp -a public/ ../deploy

      - name: Start application
        run: PM2_HOME=/root/.pm2 pm2 reload easyplan
